Auth 36 navbar
menyala-butterfly/authentick pull request #6
Opened 2022-11-02 04:02 UTC by mikexd-dev

# Pull Request Overview

### Description:

> _Write a short description for this PR_

- Reimplemented the Navbar component

### Key Changes:

> _List out key changes made in this PR_

- navbar contain search icon and connect button (disabled for now)
- search icon opens a modal similar to tailwind doc design
- navbar cater for responsiveness
- use drawer for mobile menu instead to cater for a bigger menu options in the future

<br>

---

### Link to story:

https://menyala.atlassian.net/browse/AUTH-36

2022-11-02 07:57 UTC, terrytjw commented on .github/workflows/chromatic.yml
> + push:
are we still keeping this file?

2022-11-02 07:59 UTC, terrytjw commented on components/Navbar.tsx
> +function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
change to const

2022-11-02 08:00 UTC, terrytjw commented on components/Navbar.tsx
> +function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
change to const syntax

2022-11-02 08:01 UTC, terrytjw commented on components/Navbar.tsx
> +type NavbarProps = {
Place the `NavbarProps` directly above its functional component

2022-11-02 08:03 UTC, terrytjw requested changes
just some small syntax changes, open for discussion tomorrow morning

2022-11-02 08:29 UTC, mikexd-dev commented on components/Navbar.tsx
> +function MenuIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
Updated in utils/svgs/Menu.tsx

2022-11-02 08:29 UTC, mikexd-dev commented on components/Navbar.tsx
> +function SearchIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
Updated in utils/svgs/Search.tsx

2022-11-03 02:31 UTC, terrytjw approved these changes

2022-11-03 02:31 UTC, merged